kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-redis-cluster-master-0
  labels:
    type: local
    app: redis-cluster
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/redis-cluster"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-redis-cluster-master-0
  labels:
    app: redis-cluster
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-redis-cluster-slave-0
  labels:
    type: local
    app: redis-cluster
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/redis-cluster"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-redis-cluster-slave-0
  labels:
    app: redis-cluster
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-redis-cluster-slave-1
  labels:
    type: local
    app: redis-cluster
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/redis-cluster"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-redis-cluster-slave-1
  labels:
    app: redis-cluster
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
